force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Description__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Description__c</fullName>
    <inlineHelpText>Letter of Rationale and related documents can be provided at the Upload Documents stage of the application</inlineHelpText>
    <label>Application Proposal Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Related_Application__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Related_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Sub Applications</relationshipLabel>
    <relationshipName>Parent_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MUSW__Type2__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CVRD_DS_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Contact applicant associated with the application.</description>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications as Applicant</relationshipLabel>
    <relationshipName>Application2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Phase__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MUSW__Application_Phases</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>The current status of the application. This picklist can be defined according to the client&apos;s business processes.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Type2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type2__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MUSW__Application_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application_Contact__c/fields/CVRD_DS_Primary_Owner__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Primary_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/CVRD_DS_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Form and Character - Signs</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment</fullName>
    </customValue>
    <customValue>
        <fullName>Discharge</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Use</fullName>
    </customValue>
    <customValue>
        <fullName>Non-farm Use</fullName>
    </customValue>
    <customValue>
        <fullName>Subdivision</fullName>
    </customValue>
    <customValue>
        <fullName>ALC Exclusion</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>OCP Amendment</fullName>
    </customValue>
    <customValue>
        <fullName>Zoning Amendment</fullName>
    </customValue>
    <customValue>
        <fullName>Land Use Bylaw Amendment</fullName>
    </customValue>
    <customValue>
        <fullName>Major - New</fullName>
    </customValue>
    <customValue>
        <fullName>Major - Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Minor - New</fullName>
    </customValue>
    <customValue>
        <fullName>Minor - Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Retail Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Cannabis Licence Referrals</fullName>
    </customValue>
    <customValue>
        <fullName>Change to hours</fullName>
    </customValue>
    <customValue>
        <fullName>Lounge Endorsment</fullName>
    </customValue>
    <customValue>
        <fullName>New Outdoor Patio</fullName>
    </customValue>
    <customValue>
        <fullName>New Licence</fullName>
    </customValue>
    <customValue>
        <fullName>Relocate Licence</fullName>
    </customValue>
    <customValue>
        <fullName>Increase to Capacity</fullName>
    </customValue>
    <customValue>
        <fullName>Special Event Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Special Event Permit - 150 + attendees</fullName>
    </customValue>
    <customValue>
        <fullName>Cannabis Referral License</fullName>
    </customValue>
    <customValue>
        <fullName>Delegated</fullName>
    </customValue>
    <customValue>
        <fullName>Amend an Existing Liquor License</fullName>
    </customValue>
    <customValue>
        <fullName>Relocate the Liquor License</fullName>
    </customValue>
    <description>Application Sub Types</description>
    <masterLabel>Sub Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MUSW__Application_Phases.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application</fullName>
        <default>true</default>
        <label>Application</label>
    </customValue>
    <customValue>
        <fullName>Review</fullName>
    </customValue>
    <customValue>
        <fullName>Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Hearing</fullName>
    </customValue>
    <customValue>
        <fullName>Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Close Out</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
        <isActive>false</isActive>
        <label>Closed</label>
    </customValue>
    <description>Picklist for phase on applications which is used to represent the life cycle.</description>
    <masterLabel>Application Phases</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PrintJobPDFController.cls
public class PrintJobPDFController {
    public String Id {get;set;}
    public String recordId;
    public List<MUSW__Application2__c> getApplicationList() {
        recordId = ApexPages.currentPage().getParameters().get('Id');
        System.debug(recordId);
        List<MUSW__Application2__c> appList = [Select Id, Name, MUSW__Type2__c, CVRD_DS_Description__c,
        MUSW__Applicant__c, MUSW__Status__c, CVRD_DS_Sub_Type__c, CVRD_DS_Related_Application__c, MUSW__Phase__c, MUSW__Application2__c.MUSW__Applicant__r.name From MUSW__Application2__c Where Id = :recordId];
        System.debug('Size : ' +appList.size());
        return appList;
    }

    public List<MUSW__Submission__c> getSubmissionList(){
        List<MUSW__Submission__c> subList = [Select Name, MUSW__Status__c  From MUSW__Submission__c Where MUSW__Application2__c = :recordId];
        return subList;
    }
    
    public List<MUSW__Application_Contact__c> getOwnerList(){
        List<MUSW__Application_Contact__c> ownerList = [Select Id, Name, MUSW__First_Name__c, MUSW__Last_Name__c, CVRD_DS_Primary_Owner__c From MUSW__Application_Contact__c Where MUSW__Application__c = :recordId];
        return ownerList;
    }

    public List<MUSW__Application_Location__c> getPropertyInfoList(){
        List<MUSW__Application_Location__c> pidList = [Select Name, MUSW__Parcel__r.Name, MUSW__Address__r.Name From MUSW__Application_Location__c Where MUSW__Application__c= :recordId];
        return pidList;
    }
}