force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/Agent_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Agent_Authorization__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agent Authorization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Non_Exempted_DPAs__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Non_Exempted_DPAs__c</fullName>
    <label>Non Exempted DPAs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CVRD_DS_DPAs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Selected_DPAs__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Selected_DPAs__c</fullName>
    <label>Selected DPAs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CVRD_DS_DPAs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Description__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Description__c</fullName>
    <description>Description of what the application is for.</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Phase__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MUSW__Application_Phases</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>The current status of the application. This picklist can be defined according to the client&apos;s business processes.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Type2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type2__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MUSW__Application_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Submission_List__c/fields/CVRD_DS_DPA_Types__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_DPA_Types__c</fullName>
    <label>DPA Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CVRD_DS_DPAs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CVRD_DS_DPAs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DPA 1: Riparian Protection</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 2: Sensitive Ecosystems</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 3: Marine Uplands &amp; Foreshore Protection</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 4: Aquifer Protection</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 5: Wildfire Protection</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 6: Floodplain Hazard</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 7: Landslide Hazard</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 8: Protection of Farming</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 9: Intensive Residential</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 10: Multi-family Residential Development</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 11: Commercial and Mixed Use Development</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 12: Industrial Development</fullName>
    </customValue>
    <customValue>
        <fullName>DPA 13: Energy &amp; Water Conservation, GHG Emissions Reduction</fullName>
    </customValue>
    <masterLabel>CVRD_DS_DPAs</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MUSW__Application_Phases.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application</fullName>
        <default>true</default>
        <label>Application</label>
    </customValue>
    <customValue>
        <fullName>Review</fullName>
    </customValue>
    <customValue>
        <fullName>Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Hearing</fullName>
    </customValue>
    <customValue>
        <fullName>Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Close Out</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
        <isActive>false</isActive>
        <label>Closed</label>
    </customValue>
    <description>Picklist for phase on applications which is used to represent the life cycle.</description>
    <masterLabel>Application Phases</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CVRD_DS_CreateSubmissions.cls
public class CVRD_DS_CreateSubmissions {
    
    //public static Id Development_Permit=Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Development Permit').getRecordTypeId();
    
    @InvocableMethod
    public static void createSubmissionRecords(List<ID> ids) {
        try{
            Map<Id,List<String>> selectedDPAs=new Map<Id,List<String>>();
            List<MUSW__Submission__c> SubmissionCreate=new List<MUSW__Submission__c>();
            
            List<MUSW__Application2__c> appList=[SELECT Id,MUSW__Type2__c,MUSW__Phase__c,MUSW__Status__c,CVRD_DS_Selected_DPAs__c,CVRD_DS_Non_Exempted_DPAs__c,recordtypeId,Agent_Authorization__c FROM MUSW__Application2__c WHERE Id IN: ids];        
            
            List<MUSW__Template_Object_Mapping__c> FilterObjMapping=[SELECT Id FROM MUSW__Template_Object_Mapping__c WHERE MUSW__Template_Object_Name__c='MUSW__Master_Submission_List__c' AND MUSW__Target_Object_Name__c='MUSW__Application2__c'];
            
            List<MUSW__Master_Submission_List__c> submissiontempList=[SELECT Id,Name,MUSW__Application_Phases__c,MUSW__Application_Statuses__c,MUSW__Application_Types__c,CVRD_DS_DPA_Types__c,MUSW__Submission_Description__c,MUSW__Required__c,MUSW__Submission_Name__c
                                                                      FROM MUSW__Master_Submission_List__c WHERE MUSW__Filter_Mapping__c=:FilterObjMapping AND MUSW__Active__c=true];                  
            
            for(MUSW__Master_Submission_List__c Sub_Temp:submissiontempList){
                List<String> tempDPAs=Sub_Temp.CVRD_DS_DPA_Types__c!=null?Sub_Temp.CVRD_DS_DPA_Types__c.split(';'):new List<String>();
                
                for(MUSW__Application2__c app:appList){
                    
                    List<string> SelectedDPA=app.CVRD_DS_Non_Exempted_DPAs__c!=null?app.CVRD_DS_Non_Exempted_DPAs__c.split(';'):new List<string>();
                    boolean flag=false;
                    if(Sub_Temp.MUSW__Application_Phases__c==app.MUSW__Phase__c && Sub_Temp.MUSW__Application_Statuses__c==app.MUSW__Status__c 
                       && Sub_Temp.MUSW__Application_Types__c==app.MUSW__Type2__c){
                           
                           system.debug('submission Template::'+SelectedDPA);
                           system.debug('Application Object::'+tempDPAs);
                           if(app.MUSW__Type2__c=='Development_Permit'){
                               system.debug('Inside if condition');
                               for(String strTemp:tempDPAs){
                                   if(SelectedDPA.contains(strTemp) && !flag){
                                       //system.debug('Sub_Temp::::'+Sub_Temp.Name);
                                       MUSW__Submission__c submission=new MUSW__Submission__c();
                                       submission.MUSW__Description__c=Sub_Temp.MUSW__Submission_Description__c;
                                       submission.MUSW__Application2__c =app.Id;
                                       submission.MUSW__Required__c=Sub_Temp.MUSW__Required__c;
                                       Submission.Name=Sub_temp.MUSW__Submission_Name__c;
                                       SubmissionCreate.add(Submission);
                                       flag=true;
                                   }
                               }
                           }
                           else{
                               MUSW__Submission__c submission=new MUSW__Submission__c();
                               submission.MUSW__Description__c=Sub_Temp.MUSW__Submission_Description__c;
                               submission.MUSW__Application2__c =app.Id;
                               submission.MUSW__Required__c=Sub_Temp.MUSW__Required__c;
                               Submission.Name=Sub_temp.MUSW__Submission_Name__c;
                               SubmissionCreate.add(Submission);
                           }
                       }
                    if(Sub_Temp.MUSW__Application_Phases__c==app.MUSW__Phase__c && Sub_Temp.MUSW__Application_Statuses__c==app.MUSW__Status__c
                       && Sub_Temp.Name.contains('Agent Authorization') && app.Agent_Authorization__c){
                        MUSW__Submission__c submission=new MUSW__Submission__c();
                        submission.MUSW__Description__c=Sub_Temp.MUSW__Submission_Description__c;
                        submission.MUSW__Application2__c =app.Id;
                        submission.MUSW__Required__c=Sub_Temp.MUSW__Required__c;
                        Submission.Name=Sub_temp.MUSW__Submission_Name__c;
                        SubmissionCreate.add(Submission);
                           system.debug('Inside->SubmissionCreate::'+SubmissionCreate);
                    }
                }
            }
            system.debug('SubmissionCreate::'+SubmissionCreate);
            Database.SaveResult[] lsr = Database.insert(SubmissionCreate,false);
        }catch(exception ex){
            system.debug('Exception'+ex.getmessage());
        }
    }
    
}