force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Available_for_Public_Notice__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Available_for_Public_Notice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available for Public Notice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Description__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Description__c</fullName>
    <description>Description of what the application is for.</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/CVRD_DS_Publicly_Available__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Publicly_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicly Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/cvrd_DS_Submission_FileController.cls
public without sharing class cvrd_DS_Submission_FileController {
    
    public class SubmissionDocument {
        @AuraEnabled public String contactName { get; set; }
        @AuraEnabled public id document { get; set; }
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String,List<String>> getFileId(Id ApplicationId) {
        Map<String,List<String>> SubmissionLinkMap=new Map<String,List<String>>();
        List<SubmissionDocument> SubmissionDocuments = new List<SubmissionDocument>();
        
        List<MUSW__Submission__c>sublist=[Select id,name,MUSW__View_Links__c from MUSW__Submission__C where MUSW__application2__C=:ApplicationId AND CVRD_DS_Publicly_Available__c=true ];
        
        for(MUSW__Submission__c sub:sublist){
            
            if(sub.MUSW__View_Links__c!=null && !SubmissionLinkMap.containskey(sub.name)){
                List<String> str=sub.MUSW__View_Links__c.split(',');
                SubmissionLinkMap.put(sub.name,new List<string>(str));
            }
        }
        return SubmissionLinkMap;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getFileId2(Id ApplicationId) {
                List<String> publicLinkList=new List<String>();
        List<MUSW__Application2__c> appRecord=[SELECT Id,MUSW__Description__c,CVRD_DS_Available_for_Public_Notice__c FROM MUSW__Application2__c where Id=:ApplicationId AND CVRD_DS_Available_for_Public_Notice__c=true];
        if(!appRecord.isempty()){      
            publicLinkList.add(appRecord[0].MUSW__Description__c);
            publicLinkList.add('true');
            return publicLinkList;
        }

        return publicLinkList;
    }

}