force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Description__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Description__c</fullName>
    <description>Description of what the application is for.</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/CVRD_DS_Application_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Application_Sub_Type__c</fullName>
    <label>Application Sub Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <description>The type of fee. Each type may have a different accounting code.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>File Opening Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Administrative Fee</fullName>
            </value>
            <value>
                <fullName>Advertising Fee</fullName>
            </value>
            <value>
                <fullName>Additional Fee</fullName>
            </value>
            <value>
                <fullName>Security Deposit</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/CVRD_DS_Application_DP_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Application_DP_Sub_Type__c</fullName>
    <label>Application DP Sub Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amendment/Extension(DPA 1-13)</fullName>
            </value>
            <value>
                <fullName>Conservation/GHG reduction(DPA 13)</fullName>
            </value>
            <value>
                <fullName>Agricultural(DPA 8)</fullName>
            </value>
            <value>
                <fullName>Form and Character (DPA 9-12)</fullName>
            </value>
            <value>
                <fullName>Form and Character - Signs(DPA 9-12)</fullName>
            </value>
            <value>
                <fullName>Environmental (DPA 1-4)</fullName>
            </value>
            <value>
                <fullName>Hazard (DPA 5-7)</fullName>
            </value>
            <value>
                <fullName>Environmental and Hazard(DPA 1-7)</fullName>
                <isActive>false</isActive>
                <label>Environmental and Hazard(DPA 1-7)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/CVRD_DS_Application_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Application_Sub_Type__c</fullName>
    <label>Application Sub Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CVRD_DS_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/MUSW__Type__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>File Opening Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Administrative Fee</fullName>
            </value>
            <value>
                <fullName>Advertising Fee</fullName>
            </value>
            <value>
                <fullName>Additional Fee</fullName>
            </value>
            <value>
                <fullName>Security Deposit</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CVRD_DS_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Form and Character - Signs</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment</fullName>
    </customValue>
    <customValue>
        <fullName>Discharge</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Use</fullName>
    </customValue>
    <customValue>
        <fullName>Non-farm Use</fullName>
    </customValue>
    <customValue>
        <fullName>Subdivision</fullName>
    </customValue>
    <customValue>
        <fullName>ALC Exclusion</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>OCP Amendment</fullName>
    </customValue>
    <customValue>
        <fullName>Zoning Amendment</fullName>
    </customValue>
    <customValue>
        <fullName>Land Use Bylaw Amendment</fullName>
    </customValue>
    <customValue>
        <fullName>Major - New</fullName>
    </customValue>
    <customValue>
        <fullName>Major - Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Minor - New</fullName>
    </customValue>
    <customValue>
        <fullName>Minor - Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Retail Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Cannabis Licence Referrals</fullName>
    </customValue>
    <customValue>
        <fullName>Change to hours</fullName>
    </customValue>
    <customValue>
        <fullName>Lounge Endorsment</fullName>
    </customValue>
    <customValue>
        <fullName>New Outdoor Patio</fullName>
    </customValue>
    <customValue>
        <fullName>New Licence</fullName>
    </customValue>
    <customValue>
        <fullName>Relocate Licence</fullName>
    </customValue>
    <customValue>
        <fullName>Increase to Capacity</fullName>
    </customValue>
    <customValue>
        <fullName>Special Event Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Special Event Permit - 150 + attendees</fullName>
    </customValue>
    <customValue>
        <fullName>Cannabis Referral License</fullName>
    </customValue>
    <customValue>
        <fullName>Delegated</fullName>
    </customValue>
    <customValue>
        <fullName>Amend an Existing Liquor License</fullName>
    </customValue>
    <customValue>
        <fullName>Relocate the Liquor License</fullName>
    </customValue>
    <description>Application Sub Types</description>
    <masterLabel>Sub Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CVRD_DS_Split_MultiPicklist.cls
public class CVRD_DS_Split_MultiPicklist {
    
     @InvocableMethod
    public static void splitMultipicklist(List<InputVar> InputVariable){
        
        List<String> feeTemplateSubTypeSet = new List<String>(InputVariable[0].MultipicklistValues.split(';'));
        List<MUSW__Master_Fee_List__c> feetempList=new List<MUSW__Master_Fee_List__c>(InputVariable[0].FeeTemplateRecords);
        List<MUSW__fee__c> CreateFeeList=new List<MUSW__fee__c>();
        for(MUSW__Master_Fee_List__c FeetempRecord:feetempList){
            if(feeTemplateSubTypeSet.contains(FeetempRecord.CVRD_DS_Application_DP_Sub_Type__c)){
                MUSW__fee__c feeRecords=new MUSW__Fee__c();
                feeRecords.MUSW__Type__c=FeetempRecord.MUSW__Type__c;
                feeRecords.MUSW__Description__c=FeetempRecord.MUSW__Fee_Description__c;
                feeRecords.MUSW__Amount__c=FeetempRecord.MUSW__Standard_Price__c;
                feeRecords.CVRD_DS_Application_Sub_Type__c=FeetempRecord.CVRD_DS_Application_DP_Sub_Type__c;
                feeRecords.MUSW__Application2__c=InputVariable[0].RecordId;
                CreateFeeList.add(feeRecords);
            }
        }
        Insert CreateFeeList; 
    }

	public class InputVar{
        @InvocableVariable
        public string MultipicklistValues;
        @InvocableVariable
        public List<MUSW__Master_Fee_List__c> FeeTemplateRecords;
        @InvocableVariable
        public Id RecordId;
	}
    
}