force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <description>The current status of the application. This picklist can be defined according to the client&apos;s business processes.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CVRD_DS_Get_Required_Submissions.cls
public class CVRD_DS_Get_Required_Submissions {
    
    @InvocableMethod
    public static List<string> getRequiredSubmission(List<string> recordId){
        List<MUSW__Submission__c> RequiredSubmissionList=new List<MUSW__Submission__c>();
        RequiredSubmissionList=[SELECT Id FROM MUSW__Submission__c WHERE MUSW__Application2__c IN: recordId AND MUSW__Status__c ='Pending' AND MUSW__Required__c=true];
    	system.debug('RequiredSubmissionList'+RequiredSubmissionList);
        if(!RequiredSubmissionList.isEmpty()){
            system.debug('inside if');
            return new List<String>{'false'};
        }
        else{
            system.debug('inside else');
            return new List<String>{'true'};
        }
    }
}