force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Application_Number_redirect__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Application_Number_redirect__c</fullName>
    <formula>HYPERLINK(&quot;https://cvrd--qa.sandbox.my.site.com/CVRDCitizenshipPortal/s/open-application-details?id=&quot;&amp;Id ,  Name , &quot;_self&quot;)</formula>
    <label>Application Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Parcel_Electoral_Area__c.field-meta.xml
<CustomField>
    <fullName>CVRD_DS_Parcel_Electoral_Area__c</fullName>
    <formula>MUSW__Parcel__r.CVRD_DS_Temp_Electoral_Area__c</formula>
    <label>Parcel Electoral Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Contact applicant associated with the application.</description>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications as Applicant</relationshipLabel>
    <relationshipName>Application2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Type2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Type2__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MUSW__Application_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CVRD_DS_PublicSearchController.cls
public class CVRD_DS_PublicSearchController {
  
    @AuraEnabled(cacheable=true)
    public static List<MUSW__Application2__c> getAppList(String electorialArea) {
       String str='SELECT Id,name, CVRD_DS_Application_Number_redirect__c,MUSW__Applicant__r.Name,toLabel(MUSW__Type2__c),MUSW__Address__r.Name FROM MUSW__Application2__c WHERE CVRD_DS_Parcel_Electoral_Area__c = \''+electorialArea+'\' ORDER BY Createddate DESC';
        
        return database.query(str);
    }

}